name: compile-pdf

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/typst/typst:latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile PDF
      run: |
        cp author_example.yml author.yml
        typst compile main.typ CV.pdf

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CV
        path: CV.pdf
        retention-days: 90
